globalvar
    WIDTH,HEIGHT,
    MOUSE_X,MOUSE_Y,

    TYPE,FILENAME,COMPILED,OUTPUT,TRANSPILED,TRANSPILED_TEXT,

    TTY,H3L,

    TEXT_IN,TEXT_OUT,
    SCROLL_IN,SCROLL_OUT

    COMPILE_LABEL,COMPILE_LABEL_COLOR
